# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quemiras' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FBSDKLoginKit'
  pod 'PureLayout'
  pod 'AFNetworking', '~> 4.0'
  
  target 'quemirasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'quemirasUITests' do
    # Pods for testing
  end

end
